### ISSUE TITLE
Getting invalid or corrupt torrent file when adding torrent

### ISSUE THREAD

**Issue by vipera7** [irazasyed/php-transmission-sdk#5]
## Detailed description

I want to add a torrent but I'm getting an error.

Here is the error: 

```
Fatal error: Uncaught Transmission\Exception\TransmissionException: invalid or corrupt torrent file in php-transmission-sdk/src/HttpClient/Plugin/ExceptionThrower.php:29 Stack trace: #0 
```

Here is my code : 

    require 'vendor/autoload.php';
    try{
        $transmission = new Transmission\Client($_POST['hostname'], $_POST['port'], $_POST['username'], $_POST['password']);
         //$a = $transmission->addFile("../data/slackware64-13.1-install-dvd.torrent", "/tmp");
         $a = $transmission->addFile("http://www.slackware.com/torrents/slackware64-13.1-install-dvd.torrent", "/tmp");
    } catch (Transmission\Exception\NetworkException $e) {
        echo $e->getMessage();
    }

From the doc : 

`addFile(file, savepath, optional);`

What is the difference between `add `and `addFile `?

Also it doesn't indicate if the file already exist

**Comment by irazasyed** [comment]
You can use `addFile()` if you're providing the content of the file. So its example usage would be: `addFile(file_get_contents($filepath))`.

Also, you should provide an absolute file path.

If you want to download through a magnet URI or URL, then you can make use of the `addUrl()` method.

Both of these methods are simply helpers around the main `add()` method. Add method itself can just be used for both purposes but to avoid confusion with the options, these two other methods were introduced.

As far as the duplicate is concerned, Transmission responds with the `duplicate` key which you can use to determine the added file is duplicate.

**Comment by vipera7** [comment]
Thanks you for the answer, but how can I add an arg if I want to auto start or don't start the torrent when added ?

**Comment by irazasyed** [comment]
No problem.

You can use the optional args and provide an array with your options according to the official documentation.
